name: samapi
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  dio: ^4.0.1
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  shared_preferences: ^2.0.8