name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  tools:
    git:
      url: git@github.com:samurai-o/app_tools.git
      ref: main
  samapi:
    path: ../samapi